---
version: '3.3'
services:
  freqtrade:
    build:
      context: freqtrade
      args:
        BINANCE_API_KEY: ${BINANCE_API_KEY}
        BINANCE_API_SECRET_KEY: ${BINANCE_API_SECRET_KEY}
        FREQ_API_PWD: ${FREQ_API_PWD}
        TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
        TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    restart: unless-stopped
    container_name: freqtrade
    ports:
      - "8080:8080"
    volumes:
      - "./freqtrade/user_data:/freqtrade/user_data"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /tmp/config.json
      --strategy CombinedBinHAndCluc 
    healthcheck:
      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8080/api/v1/ping}"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - freqtrade_net
networks:
  freqtrade_net:
